if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi


##
# Your previous /Users/nningego/.bash_profile file was backed up as /Users/nningego/.bash_profile.macports-saved_2013-01-11_at_10:13:21
##

# MacPorts Installer addition on 2013-01-11_at_10:13:21: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

eval "$(rbenv init -)"